### ISSUE TITLE
ValueError: Cannot load file containing pickled data when allow_pickle=False

### ISSUE THREAD

**Issue by renespeck** [WDAqua/ReMatch#1]
Hi, 
I try to run the server because I want to reproduce the evaluation. 
My first question is, if it's the correct way to run the evaluation. 
Or how to reproduce the files in the Evaluation folder? 

Regarding the error. I installed everything also  a new textrazor API key and the glove data. 

1. I run the `main.py` and terminates without an error or a message. 
2. I run the server (` python webService.py 8080`)

Then I execute with curl:  `curl http://localhost:8080/Obama%20married%20Michel%20in%201999.` and get the curls response : `curl: (52) Empty reply from server`

On the server side I get: 

```
Exception happened during processing of request from ('127.0.0.1', 48602)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "webService.py", line 41, in do_GET
    self.init()
  File "webService.py", line 27, in init
    self.mat=base.np.load('mat.dat')
  File "/home/rspeck/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 451, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False
```
system: (Ubuntu 18.04.2 LTS, Python 2.7.15+)

For any help I would be very thankful.

**Comment by renespeck** [comment]
I downgraded numpy to 1.16.2 and the error (Cannot load file containing pickled data when allow_pickle=False) is gone.

But with my request, I don't get an answer from the server. 
So still: `curl: (52) Empty reply from server` .

What I'm doing wrong?

**Comment by renespeck** [comment]
I realized that I have to start the server with Admin rights and to download some data with 

```import nltk
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')
nltk.download('wordnet') 
```

Now it seems to work. 

Would be cool if you update the README. =)
